### ISSUE TITLE
在 'fis release -o' optimizer 之前 autoprefixer.process 返回的是对象（应该是文本内容）会造成 release 报错。

### ISSUE THREAD

**Issue by aftdotleo** [ZoomZhao/fis-postprocessor-autoprefixer#2]
Hi @ZoomZhao ,

问题原因：在 **index.js** 里的 `return processor.process(content, conf);` 返回的是个对象

1. 当执行 fis release 时不会执行 optimizer，所以不会报错；
2. 当执行 fis release -o 时，执行到 optimizer.clean-css 时会在 replace 函数的 `data.replace.apply(data, arguments);` 报错，process 返回的对象没有 replace 函数的，apply 会报 undefined。

参见 **https://github.com/postcss/autoprefixe**，可以得知返回内容的写法是 `return processor.process(content, conf).css;`

![23313a68-79ab-4049-be20-134351776514](https://cloud.githubusercontent.com/assets/2201795/5700597/81ee63da-9a7b-11e4-8bdd-102ab9d867c6.png)

**Comment by ZoomZhao** [comment]
感谢 @aftdotleo 
已经修改，并发布到 NPM
