### ISSUE TITLE
5.2.1控制台报错

### ISSUE THREAD

**Issue by petsa** [ZoomZhao/fis-postprocessor-autoprefixer#3]
报错信息：.Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

5.1.7没有这个报错

**Comment by memoryza** [comment]
已经fixed，在github上拉取最新代码就好了，Autoprefixer 升级到5.2.0以后（postcss升级到4.1.1以上接口变更了）就会把这个信息打印出来 @ZoomZhao  在commit的时候忘记更改package.json中的版本号和autoprefixer依赖的版本号了

**Comment by hefangshi** [comment]
建议把版本号固定一下，或者在小版本使用^来匹配。大版本更新很容易出现breaking change

**Comment by ZoomZhao** [comment]
@hefangshi 好的，使用了 ^ 来匹配版本
